FROM php:8.4-apache

# Ambil script installer ekstensi resmi PHP
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

# Install seluruh ekstensi Laravel dalam 1 baris cepat
RUN install-php-extensions pdo_sqlite pdo_mysql bcmath gd intl zip opcache \
    && a2enmod rewrite

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/laravel
COPY . .

# Setup Apache symlink & config
RUN rm -rf /var/www/html && ln -s /var/www/laravel/public /var/www/html

# Setup env, session, composer, dan key
RUN cp .env.example .env \
    && sed -i 's/^SESSION_DRIVER=.*/SESSION_DRIVER=array/' .env \
    && composer install --optimize-autoloader --no-interaction \
    && php artisan key:generate

# Setup SQLite & permission folder Laravel
RUN mkdir -p database storage bootstrap/cache \
    && touch database/database.sqlite \
    && chown -R www-data:www-data /var/www/laravel/storage /var/www/laravel/bootstrap/cache /var/www/laravel/database \
    && chmod -R 775 /var/www/laravel/storage /var/www/laravel/bootstrap/cache /var/www/laravel/database

EXPOSE 80

CMD ["apache2-foreground"]
