[build]
  functions = "netlify/functions"

[functions]
  included_files = ["frankenphp", "phpMyAdmin-5.2.3-english/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true