version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable # Gunakan image dasar CircleCI
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/test:latest .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/test:latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - build