name: Deploy on Push
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to cPanel
              run: |
                  curl --location 'https://ozan.my.id:2083/execute/VersionControl/update' \
                    --header 'Authorization: cpanel ${{ secrets.CPANEL_USER }}:${{ secrets.CPANEL_API_KEY }}' \
                    --header 'Content-Type: application/json' \
                    --data '{
                        "repository_root": "/home/nbobimkb/public_html/ozan.my.id",
                        "branch": "master"
                    }'
