name: Deploy website on push
on:
  push:
    branches:
      - master
      
jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Sesuaikan versi PHP yang Anda gunakan
        
      - name: Check for composer.json and run composer install if needed
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader;
        
      - name: Create vendor.zip
        run: zip -r vendor.zip vendor

      - name: Sync files via FTP excluding vendor directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          exclude:
            - 'vendor/**'
            - '.git/**'
